"""add_unique_constraint_student_opportunity

Revision ID: 9788eccd3cba
Revises: 489bb7154375
Create Date: 2026-03-15 05:05:07.523448
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9788eccd3cba'
down_revision: Union[str, None] = '489bb7154375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_student_opportunity', 'applications', ['student_id', 'opportunity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_opportunity', 'applications', type_='unique')
    # ### end Alembic commands ###
